"""Add food_items table

Revision ID: 43e3a1fbbc43
Revises: add_user_phone_fields
Create Date: 2025-09-20 15:23:04.571514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e3a1fbbc43'
down_revision: Union[str, Sequence[str], None] = 'add_user_phone_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create food_items table
    op.create_table('food_items',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('fodmap_level', sa.String(length=20), nullable=False),
        sa.Column('calories_per_100g', sa.Float(), nullable=True),
        sa.Column('fiber_per_100g', sa.Float(), nullable=True),
        sa.Column('fat_per_100g', sa.Float(), nullable=True),
        sa.Column('protein_per_100g', sa.Float(), nullable=True),
        sa.Column('carbs_per_100g', sa.Float(), nullable=True),
        sa.Column('common_triggers', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    
    # Skip problematic column alterations for now
    # op.alter_column('diet_logs', 'portion_size_g',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            type_=sa.Numeric(precision=10, scale=2),
    #            existing_nullable=True)
    # op.alter_column('diet_logs', 'time_since_last_meal_hours',
    #            existing_type=sa.DOUBLE_PRECISION(precision=53),
    #            type_=sa.Numeric(precision=5, scale=2),
    #            existing_nullable=True)
    # op.drop_index('ix_diet_logs_consumed_at', table_name='diet_logs')
    # op.drop_index('ix_diet_logs_meal_type', table_name='diet_logs')
    # op.alter_column('food_reactions', 'diet_log_id',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.UUID(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop food_items table
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_table('food_items')
    
    # Skip problematic column alterations for now
    # op.alter_column('food_reactions', 'diet_log_id',
    #            existing_type=sa.UUID(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # op.create_index('ix_diet_logs_meal_type', 'diet_logs', ['meal_type'], unique=False)
    # op.create_index('ix_diet_logs_consumed_at', 'diet_logs', ['consumed_at'], unique=False)
    # op.alter_column('diet_logs', 'time_since_last_meal_hours',
    #            existing_type=sa.Numeric(precision=5, scale=2),
    #            type_=sa.DOUBLE_PRECISION(precision=53),
    #            existing_nullable=True)
    # op.alter_column('diet_logs', 'portion_size_g',
    #            existing_type=sa.Numeric(precision=10, scale=2),
    #            type_=sa.DOUBLE_PRECISION(precision=53),
    #            existing_nullable=True)
    # ### end Alembic commands ###
