"""Add MLPrediction model

Revision ID: 6400c81dd578
Revises: a12d6f06fd63
Create Date: 2025-09-22 14:40:46.205079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6400c81dd578'
down_revision: Union[str, Sequence[str], None] = 'a12d6f06fd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ml_predictions table
    op.create_table('ml_predictions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('prediction_type', sa.String(length=50), nullable=False),
        sa.Column('model_version', sa.String(length=100), nullable=True),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('prediction_data', sa.JSON(), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('predicted_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_user_id'), 'ml_predictions', ['user_id'], unique=False)
    
    # Skip the problematic foreign key constraint for now
    op.create_index(op.f('ix_food_reactions_diet_log_id'), 'food_reactions', ['diet_log_id'], unique=False)
    # op.create_foreign_key(op.f('fk_food_reactions_diet_log_id_diet_logs'), 'food_reactions', 'diet_logs', ['diet_log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('fk_food_reactions_diet_log_id_diet_logs'), 'food_reactions', type_='foreignkey')
    op.drop_index(op.f('ix_food_reactions_diet_log_id'), table_name='food_reactions')
    
    # Drop ml_predictions table
    op.drop_index(op.f('ix_ml_predictions_user_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    # ### end Alembic commands ###
