"""fix_food_reactions_diet_log_id_data_type

Revision ID: 687d42966a35
Revises: 6400c81dd578
Create Date: 2025-09-30 12:38:10.828763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687d42966a35'
down_revision: Union[str, Sequence[str], None] = '6400c81dd578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_reactions', 'diet_log_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_food_reactions_diet_log_id'), 'food_reactions', ['diet_log_id'], unique=False)
    op.create_foreign_key(op.f('fk_food_reactions_diet_log_id_diet_logs'), 'food_reactions', 'diet_logs', ['diet_log_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_food_reactions_diet_log_id_diet_logs'), 'food_reactions', type_='foreignkey')
    op.drop_index(op.f('ix_food_reactions_diet_log_id'), table_name='food_reactions')
    op.alter_column('food_reactions', 'diet_log_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
