"""Add UserPreferences model

Revision ID: 8fb5a5c7c9aa
Revises: af858f767fde
Create Date: 2025-10-03 11:35:55.100583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fb5a5c7c9aa'
down_revision: Union[str, Sequence[str], None] = 'af858f767fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_billing_addresses_user_id_users', 'billing_addresses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_billing_addresses_user_id_users'), 'billing_addresses', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_challenge_participations_user_id_users', 'challenge_participations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_challenge_participations_user_id_users'), 'challenge_participations', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_challenges_created_by_user_id_users', 'challenges', type_='foreignkey')
    op.create_foreign_key(op.f('fk_challenges_created_by_user_id_users'), 'challenges', 'users', ['created_by_user_id'], ['id'])
    op.drop_constraint('fk_data_insights_user_id_users', 'data_insights', type_='foreignkey')
    op.create_foreign_key(op.f('fk_data_insights_user_id_users'), 'data_insights', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_device_tokens_user_id_users', 'device_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('fk_device_tokens_user_id_users'), 'device_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_diet_logs_user_id_users', 'diet_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_diet_logs_user_id_users'), 'diet_logs', 'users', ['user_id'], ['id'])
    op.alter_column('food_reactions', 'diet_log_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_constraint('fk_food_reactions_user_id_users', 'food_reactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_food_reactions_user_id_users'), 'food_reactions', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_goal_progress_user_id_users', 'goal_progress', type_='foreignkey')
    op.create_foreign_key(op.f('fk_goal_progress_user_id_users'), 'goal_progress', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_invoices_user_id_users', 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoices_user_id_users'), 'invoices', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_medical_records_user_id_users', 'medical_records', type_='foreignkey')
    op.create_foreign_key(op.f('fk_medical_records_user_id_users'), 'medical_records', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_medication_costs_user_id_users', 'medication_costs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_medication_costs_user_id_users'), 'medication_costs', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_medication_logs_user_id_users', 'medication_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_medication_logs_user_id_users'), 'medication_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_milestones_user_id_users', 'milestones', type_='foreignkey')
    op.create_foreign_key(op.f('fk_milestones_user_id_users'), 'milestones', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_notification_preferences_user_id_users', 'notification_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notification_preferences_user_id_users'), 'notification_preferences', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_notifications_user_id_users', 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notifications_user_id_users'), 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_payment_methods_user_id_users', 'payment_methods', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payment_methods_user_id_users'), 'payment_methods', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_report_generations_user_id_users', 'report_generations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_report_generations_user_id_users'), 'report_generations', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_subscriptions_user_id_users', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subscriptions_user_id_users'), 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_symptom_logs_user_id_users', 'symptom_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_symptom_logs_user_id_users'), 'symptom_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_transactions_user_id_users', 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_transactions_user_id_users'), 'transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_user_achievements_user_id_users', 'user_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_achievements_user_id_users'), 'user_achievements', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_user_analytics_user_id_users', 'user_analytics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_analytics_user_id_users'), 'user_analytics', 'users', ['user_id'], ['id'])
    op.alter_column('user_goals', 'frequency',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='goalfrequencyenum'),
               nullable=False)
    op.alter_column('user_goals', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', 'EXPIRED', name='goalstatusenum'),
               nullable=False)
    op.create_index(op.f('ix_user_goals_goal_type'), 'user_goals', ['goal_type'], unique=False)
    op.drop_constraint('fk_user_goals_user_id_users', 'user_goals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_goals_user_id_users'), 'user_goals', 'users', ['user_id'], ['id'])
    op.drop_constraint('fk_user_providers_user_id_users', 'user_providers', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_providers_user_id_users'), 'user_providers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_providers_user_id_users'), 'user_providers', type_='foreignkey')
    op.create_foreign_key('fk_user_providers_user_id_users', 'user_providers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_goals_user_id_users'), 'user_goals', type_='foreignkey')
    op.create_foreign_key('fk_user_goals_user_id_users', 'user_goals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_goals_goal_type'), table_name='user_goals')
    op.alter_column('user_goals', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', 'EXPIRED', name='goalstatusenum'),
               nullable=True)
    op.alter_column('user_goals', 'frequency',
               existing_type=postgresql.ENUM('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='goalfrequencyenum'),
               nullable=True)
    op.drop_constraint(op.f('fk_user_analytics_user_id_users'), 'user_analytics', type_='foreignkey')
    op.create_foreign_key('fk_user_analytics_user_id_users', 'user_analytics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_user_achievements_user_id_users'), 'user_achievements', type_='foreignkey')
    op.create_foreign_key('fk_user_achievements_user_id_users', 'user_achievements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_transactions_user_id_users'), 'transactions', type_='foreignkey')
    op.create_foreign_key('fk_transactions_user_id_users', 'transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_symptom_logs_user_id_users'), 'symptom_logs', type_='foreignkey')
    op.create_foreign_key('fk_symptom_logs_user_id_users', 'symptom_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_subscriptions_user_id_users'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key('fk_subscriptions_user_id_users', 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_report_generations_user_id_users'), 'report_generations', type_='foreignkey')
    op.create_foreign_key('fk_report_generations_user_id_users', 'report_generations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_payment_methods_user_id_users'), 'payment_methods', type_='foreignkey')
    op.create_foreign_key('fk_payment_methods_user_id_users', 'payment_methods', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_notifications_user_id_users'), 'notifications', type_='foreignkey')
    op.create_foreign_key('fk_notifications_user_id_users', 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_notification_preferences_user_id_users'), 'notification_preferences', type_='foreignkey')
    op.create_foreign_key('fk_notification_preferences_user_id_users', 'notification_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_milestones_user_id_users'), 'milestones', type_='foreignkey')
    op.create_foreign_key('fk_milestones_user_id_users', 'milestones', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_medication_logs_user_id_users'), 'medication_logs', type_='foreignkey')
    op.create_foreign_key('fk_medication_logs_user_id_users', 'medication_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_medication_costs_user_id_users'), 'medication_costs', type_='foreignkey')
    op.create_foreign_key('fk_medication_costs_user_id_users', 'medication_costs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_medical_records_user_id_users'), 'medical_records', type_='foreignkey')
    op.create_foreign_key('fk_medical_records_user_id_users', 'medical_records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_invoices_user_id_users'), 'invoices', type_='foreignkey')
    op.create_foreign_key('fk_invoices_user_id_users', 'invoices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_goal_progress_user_id_users'), 'goal_progress', type_='foreignkey')
    op.create_foreign_key('fk_goal_progress_user_id_users', 'goal_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_food_reactions_user_id_users'), 'food_reactions', type_='foreignkey')
    op.create_foreign_key('fk_food_reactions_user_id_users', 'food_reactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('food_reactions', 'diet_log_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_diet_logs_user_id_users'), 'diet_logs', type_='foreignkey')
    op.create_foreign_key('fk_diet_logs_user_id_users', 'diet_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_device_tokens_user_id_users'), 'device_tokens', type_='foreignkey')
    op.create_foreign_key('fk_device_tokens_user_id_users', 'device_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_data_insights_user_id_users'), 'data_insights', type_='foreignkey')
    op.create_foreign_key('fk_data_insights_user_id_users', 'data_insights', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_challenges_created_by_user_id_users'), 'challenges', type_='foreignkey')
    op.create_foreign_key('fk_challenges_created_by_user_id_users', 'challenges', 'users', ['created_by_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_challenge_participations_user_id_users'), 'challenge_participations', type_='foreignkey')
    op.create_foreign_key('fk_challenge_participations_user_id_users', 'challenge_participations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_billing_addresses_user_id_users'), 'billing_addresses', type_='foreignkey')
    op.create_foreign_key('fk_billing_addresses_user_id_users', 'billing_addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
