"""Add analytics, notifications, goals, and appointments models

Revision ID: a12d6f06fd63
Revises: add_financial_tables
Create Date: 2025-09-22 10:37:26.466613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a12d6f06fd63'
down_revision: Union[str, Sequence[str], None] = 'add_financial_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('achievement_type', sa.Enum('MILESTONE', 'STREAK', 'IMPROVEMENT', 'CONSISTENCY', 'DISCOVERY', 'SPECIAL', name='achievementtypeenum'), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('badge_color', sa.String(length=7), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('name', name=op.f('uq_achievements_name'))
    )
    op.create_table('healthcare_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('provider_type', sa.Enum('PRIMARY_CARE', 'GASTROENTEROLOGIST', 'NUTRITIONIST', 'DIETITIAN', 'THERAPIST', 'PSYCHIATRIST', 'SPECIALIST', 'NURSE_PRACTITIONER', 'PHYSICIAN_ASSISTANT', name='providertypeenum'), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('office_address', sa.JSON(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('npi_number', sa.String(length=20), nullable=True),
    sa.Column('practice_name', sa.String(length=200), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('external_provider_id', sa.String(length=100), nullable=True),
    sa.Column('accepts_telemedicine', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('languages_spoken', sa.JSON(), nullable=True),
    sa.Column('insurance_accepted', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_healthcare_providers'))
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('notification_type', sa.Enum('MEDICATION_REMINDER', 'SYMPTOM_LOG_REMINDER', 'DIET_LOG_REMINDER', 'APPOINTMENT_REMINDER', 'HEALTH_INSIGHT', 'SYSTEM_UPDATE', 'ACHIEVEMENT', 'RECOMMENDATION', 'ALERT', 'EDUCATIONAL', name='notificationtypeenum'), nullable=False),
    sa.Column('title_template', sa.String(length=200), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriorityenum'), nullable=True),
    sa.Column('default_channels', sa.JSON(), nullable=True),
    sa.Column('required_variables', sa.JSON(), nullable=True),
    sa.Column('optional_variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_notification_templates_name'))
    )
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('metric_category', sa.String(length=50), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_metrics'))
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('appointment_type', sa.Enum('CONSULTATION', 'FOLLOW_UP', 'EMERGENCY', 'ROUTINE_CHECKUP', 'SPECIALIST', 'TELEMEDICINE', 'PROCEDURE', 'LAB_WORK', 'IMAGING', 'THERAPY', name='appointmenttypeenum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'RESCHEDULED', 'CANCELLED', 'COMPLETED', 'NO_SHOW', 'IN_PROGRESS', name='appointmentstatusenum'), nullable=True),
    sa.Column('is_telemedicine', sa.Boolean(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('preparation_instructions', sa.Text(), nullable=True),
    sa.Column('required_documents', sa.JSON(), nullable=True),
    sa.Column('fasting_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_in_days', sa.Integer(), nullable=True),
    sa.Column('external_appointment_id', sa.String(length=100), nullable=True),
    sa.Column('booking_reference', sa.String(length=50), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['healthcare_providers.id'], name=op.f('fk_appointments_provider_id_healthcare_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_appointments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_table('challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('points_reward', sa.Integer(), nullable=True),
    sa.Column('badge_reward', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_challenges_created_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenges'))
    )
    op.create_table('data_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('supporting_data', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('actionable', sa.Boolean(), nullable=True),
    sa.Column('viewed_by_user', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_data_insights_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_insights'))
    )
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=200), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_device_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_device_tokens_token'))
    )
    op.create_table('milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('milestone_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('importance_level', sa.Integer(), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=True),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_milestones_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('sms_enabled', sa.Boolean(), nullable=True),
    sa.Column('medication_reminders', sa.Boolean(), nullable=True),
    sa.Column('symptom_log_reminders', sa.Boolean(), nullable=True),
    sa.Column('diet_log_reminders', sa.Boolean(), nullable=True),
    sa.Column('appointment_reminders', sa.Boolean(), nullable=True),
    sa.Column('health_insights', sa.Boolean(), nullable=True),
    sa.Column('system_updates', sa.Boolean(), nullable=True),
    sa.Column('achievements', sa.Boolean(), nullable=True),
    sa.Column('recommendations', sa.Boolean(), nullable=True),
    sa.Column('alerts', sa.Boolean(), nullable=True),
    sa.Column('educational', sa.Boolean(), nullable=True),
    sa.Column('digest_frequency', sa.String(length=20), nullable=True),
    sa.Column('minimum_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriorityenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_notification_preferences_user_id'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('MEDICATION_REMINDER', 'SYMPTOM_LOG_REMINDER', 'DIET_LOG_REMINDER', 'APPOINTMENT_REMINDER', 'HEALTH_INSIGHT', 'SYSTEM_UPDATE', 'ACHIEVEMENT', 'RECOMMENDATION', 'ALERT', 'EDUCATIONAL', name='notificationtypeenum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriorityenum'), nullable=True),
    sa.Column('delivery_channels', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'READ', 'DISMISSED', 'FAILED', name='notificationstatusenum'), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('notification_metadata', sa.JSON(), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=100), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('report_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_title', sa.String(length=200), nullable=False),
    sa.Column('report_format', sa.String(length=20), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=False),
    sa.Column('date_range_end', sa.DateTime(), nullable=False),
    sa.Column('filters_applied', sa.JSON(), nullable=True),
    sa.Column('report_data', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('generation_status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_generations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_generations'))
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_user_achievements_achievement_id_achievements')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_achievements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievements'))
    )
    op.create_table('user_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('total_symptom_logs', sa.Integer(), nullable=True),
    sa.Column('average_symptom_severity', sa.Float(), nullable=True),
    sa.Column('most_common_symptoms', sa.JSON(), nullable=True),
    sa.Column('symptom_frequency_score', sa.Float(), nullable=True),
    sa.Column('total_diet_logs', sa.Integer(), nullable=True),
    sa.Column('total_food_reactions', sa.Integer(), nullable=True),
    sa.Column('trigger_foods_identified', sa.JSON(), nullable=True),
    sa.Column('safe_foods_identified', sa.JSON(), nullable=True),
    sa.Column('nutrition_adherence_score', sa.Float(), nullable=True),
    sa.Column('total_medication_logs', sa.Integer(), nullable=True),
    sa.Column('medication_adherence_rate', sa.Float(), nullable=True),
    sa.Column('missed_doses_count', sa.Integer(), nullable=True),
    sa.Column('side_effects_reported', sa.Integer(), nullable=True),
    sa.Column('average_stress_level', sa.Float(), nullable=True),
    sa.Column('average_sleep_quality', sa.Float(), nullable=True),
    sa.Column('exercise_frequency', sa.Float(), nullable=True),
    sa.Column('health_improvement_score', sa.Float(), nullable=True),
    sa.Column('quality_of_life_score', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_analytics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_analytics'))
    )
    op.create_table('user_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_type', sa.Enum('SYMPTOM_REDUCTION', 'MEDICATION_ADHERENCE', 'DIET_TRACKING', 'EXERCISE', 'STRESS_MANAGEMENT', 'SLEEP_QUALITY', 'WEIGHT_MANAGEMENT', 'TRIGGER_IDENTIFICATION', 'CUSTOM', name='goaltypeenum'), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('target_unit', sa.String(length=50), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='goalfrequencyenum'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', 'EXPIRED', name='goalstatusenum'), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_track', sa.Boolean(), nullable=True),
    sa.Column('goal_metadata', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goals'))
    )
    op.create_table('user_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('can_view_data', sa.Boolean(), nullable=True),
    sa.Column('can_receive_reports', sa.Boolean(), nullable=True),
    sa.Column('data_sharing_consent', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['healthcare_providers.id'], name=op.f('fk_user_providers_provider_id_healthcare_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_providers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_providers'))
    )
    op.create_table('appointment_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('is_visible_to_user', sa.Boolean(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_notes_appointment_id_appointments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_notes'))
    )
    op.create_table('appointment_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('reminder_time', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=True),
    sa.Column('delivery_method', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_appointment_reminders_appointment_id_appointments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment_reminders'))
    )
    op.create_table('challenge_participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_progress', sa.Float(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('progress_data', sa.JSON(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name=op.f('fk_challenge_participations_challenge_id_challenges')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_challenge_participations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_challenge_participations'))
    )
    op.create_table('goal_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('progress_date', sa.Date(), nullable=False),
    sa.Column('value_achieved', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('related_logs', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['user_goals.id'], name=op.f('fk_goal_progress_goal_id_user_goals')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goal_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_progress'))
    )
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('external_record_id', sa.String(length=100), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('access_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('fk_medical_records_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['provider_id'], ['healthcare_providers.id'], name=op.f('fk_medical_records_provider_id_healthcare_providers')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medical_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records'))
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'PUSH', 'EMAIL', 'SMS', name='deliverychannelenum'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_code', sa.String(length=10), nullable=True),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_logs_notification_id_notifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs'))
    )
    op.drop_table('user_profile_completion')
    op.drop_table('user_dietary_profiles')
    op.drop_table('user_preferences')
    op.drop_table('user_medical_profiles')
    op.add_column('billing_addresses', sa.Column('street_address', sa.String(length=255), nullable=False))
    op.alter_column('billing_addresses', 'country',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_column('billing_addresses', 'address_line_2')
    op.drop_column('billing_addresses', 'is_active')
    op.drop_column('billing_addresses', 'last_name')
    op.drop_column('billing_addresses', 'company')
    op.drop_column('billing_addresses', 'first_name')
    op.drop_column('billing_addresses', 'address_line_1')
    op.alter_column('diet_logs', 'portion_size_g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('diet_logs', 'time_since_last_meal_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_diet_logs_consumed_at'), table_name='diet_logs')
    op.drop_index(op.f('ix_diet_logs_meal_type'), table_name='diet_logs')
    # Since the table is empty, we can safely drop and recreate the column
    op.drop_column('food_reactions', 'diet_log_id')
    op.add_column('food_reactions', sa.Column('diet_log_id', sa.UUID(), nullable=True))
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.add_column('payment_methods', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('payment_methods', sa.Column('cardholder_name', sa.String(length=100), nullable=True))
    op.alter_column('payment_methods', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payment_methods', 'provider_payment_method_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_payment_methods_payment_type'), table_name='payment_methods')
    op.create_index(op.f('ix_payment_methods_type'), 'payment_methods', ['type'], unique=False)
    op.drop_column('payment_methods', 'is_active')
    op.drop_column('payment_methods', 'payment_type')
    op.drop_column('payment_methods', 'card_brand')
    op.drop_column('payment_methods', 'nickname')
    op.drop_column('payment_methods', 'account_type')
    op.drop_column('payment_methods', 'bank_name')
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=postgresql.ENUM('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'ONE_TIME', name='billingcycleenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('transactions', sa.Column('type', sa.String(length=50), nullable=False))
    op.alter_column('transactions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatusenum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.create_index(op.f('ix_transactions_type'), 'transactions', ['type'], unique=False)
    op.drop_column('transactions', 'transaction_type')
    op.alter_column('users', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=20),
               type_=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender_enum'),
               existing_nullable=True,
               postgresql_using="gender::gender_enum")
    op.alter_column('users', 'ibs_type',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('IBS_C', 'IBS_D', 'IBS_M', 'IBS_U', name='ibs_type_enum'),
               existing_nullable=True,
               postgresql_using="ibs_type::ibs_type_enum")
    op.alter_column('users', 'diagnosis_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('users', 'height_cm',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('users', 'privacy_settings',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'privacy_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'height_cm',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'diagnosis_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'ibs_type',
               existing_type=postgresql.ENUM('IBS_C', 'IBS_D', 'IBS_M', 'IBS_U', name='ibs_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('transactions', sa.Column('transaction_type', postgresql.ENUM('SUBSCRIPTION', 'MEDICATION_PURCHASE', 'CONSULTATION_FEE', 'PREMIUM_FEATURE', 'REFUND', 'ADJUSTMENT', 'OTHER', name='transactiontypeenum'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_type'), table_name='transactions')
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.alter_column('transactions', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatusenum'),
               existing_nullable=False)
    op.drop_column('transactions', 'type')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('subscriptions', 'billing_cycle',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'ANNUAL', 'ONE_TIME', name='billingcycleenum'),
               existing_nullable=False)
    op.add_column('payment_methods', sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payment_methods', sa.Column('account_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('payment_methods', sa.Column('nickname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payment_methods', sa.Column('card_brand', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('payment_methods', sa.Column('payment_type', postgresql.ENUM('CREDIT_CARD', 'DEBIT_CARD', 'BANK_ACCOUNT', 'PAYPAL', 'APPLE_PAY', 'GOOGLE_PAY', 'STRIPE', 'OTHER', name='paymentmethodtypeenum'), autoincrement=False, nullable=False))
    op.add_column('payment_methods', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_payment_methods_type'), table_name='payment_methods')
    op.create_index(op.f('ix_payment_methods_payment_type'), 'payment_methods', ['payment_type'], unique=False)
    op.alter_column('payment_methods', 'provider_payment_method_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('payment_methods', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('payment_methods', 'cardholder_name')
    op.drop_column('payment_methods', 'type')
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # Recreate the column as INTEGER for downgrade
    op.drop_column('food_reactions', 'diet_log_id')
    op.add_column('food_reactions', sa.Column('diet_log_id', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_diet_logs_meal_type'), 'diet_logs', ['meal_type'], unique=False)
    op.create_index(op.f('ix_diet_logs_consumed_at'), 'diet_logs', ['consumed_at'], unique=False)
    op.alter_column('diet_logs', 'time_since_last_meal_hours',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('diet_logs', 'portion_size_g',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('billing_addresses', sa.Column('address_line_1', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('billing_addresses', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('billing_addresses', sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('billing_addresses', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('billing_addresses', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('billing_addresses', sa.Column('address_line_2', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('billing_addresses', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=2),
               existing_nullable=False)
    op.drop_column('billing_addresses', 'street_address')
    op.create_table('user_medical_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('height_cm', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('ibs_type', postgresql.ENUM('IBS_C', 'IBS_D', 'IBS_M', 'IBS_U', 'NOT_DIAGNOSED', name='ibstype'), autoincrement=False, nullable=True),
    sa.Column('diagnosis_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('severity_level', postgresql.ENUM('MILD', 'MODERATE', 'SEVERE', name='severitylevel'), autoincrement=False, nullable=True),
    sa.Column('medical_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allergies', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('current_medications', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('other_conditions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('stress_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sleep_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_frequency', postgresql.ENUM('NONE', 'LIGHT', 'MODERATE', 'INTENSE', name='exercisefrequency'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_medical_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_medical_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_medical_profiles_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('privacy_settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('communication_preferences', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('primary_goals', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('preferred_treatments', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('theme_preference', postgresql.ENUM('LIGHT', 'DARK', 'SYSTEM', name='themepreference'), autoincrement=False, nullable=False),
    sa.Column('language_preference', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_dietary_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dietary_restrictions', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('known_food_triggers', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('preferred_foods', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('foods_to_avoid', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('meals_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eating_schedule', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('follows_special_diet', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('special_diet_types', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_dietary_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_dietary_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_dietary_profiles_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('user_profile_completion',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('basic_info_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('medical_history_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('dietary_preferences_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('lifestyle_factors_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('goals_preferences_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('completion_percentage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profile_completion_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile_completion')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profile_completion_user_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('notification_logs')
    op.drop_table('medical_records')
    op.drop_table('goal_progress')
    op.drop_table('challenge_participations')
    op.drop_table('appointment_reminders')
    op.drop_table('appointment_notes')
    op.drop_table('user_providers')
    op.drop_table('user_goals')
    op.drop_table('user_analytics')
    op.drop_table('user_achievements')
    op.drop_table('report_generations')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_table('milestones')
    op.drop_table('device_tokens')
    op.drop_table('data_insights')
    op.drop_table('challenges')
    op.drop_table('appointments')
    op.drop_table('system_metrics')
    op.drop_table('notification_templates')
    op.drop_table('healthcare_providers')
    op.drop_table('achievements')
    # ### end Alembic commands ###
