"""Initial migration with all models

Revision ID: f5d9c929dc01
Revises: 
Create Date: 2025-09-15 15:44:28.742225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d9c929dc01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('GRAINS', 'VEGETABLES', 'FRUITS', 'PROTEINS', 'DAIRY', 'FATS_OILS', 'BEVERAGES', 'SNACKS', 'CONDIMENTS', 'SUPPLEMENTS', name='foodcategoryenum'), nullable=False),
    sa.Column('calories_per_100g', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('fodmap_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'UNKNOWN', name='fodmaplevelenum'), nullable=True),
    sa.Column('fodmap_details', sa.Text(), nullable=True),
    sa.Column('common_triggers', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('allergens', sa.Text(), nullable=True),
    sa.Column('preparation_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    op.create_index(op.f('ix_foods_fodmap_level'), 'foods', ['fodmap_level'], unique=False)
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=200), nullable=True),
    sa.Column('medication_type', sa.Enum('PRESCRIPTION', 'OTC', 'SUPPLEMENT', 'PROBIOTIC', 'HERBAL', name='medicationtypeenum'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('therapeutic_class', sa.String(length=100), nullable=True),
    sa.Column('active_ingredients', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('interactions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    op.create_index(op.f('ix_medications_category'), 'medications', ['category'], unique=False)
    op.create_index(op.f('ix_medications_generic_name'), 'medications', ['generic_name'], unique=False)
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_medication_type'), 'medications', ['medication_type'], unique=False)
    op.create_index(op.f('ix_medications_name'), 'medications', ['name'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptoms'))
    )
    op.create_index(op.f('ix_symptoms_category'), 'symptoms', ['category'], unique=False)
    op.create_index(op.f('ix_symptoms_id'), 'symptoms', ['id'], unique=False)
    op.create_index(op.f('ix_symptoms_name'), 'symptoms', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='genderenum'), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('ibs_type', sa.Enum('IBS_C', 'IBS_D', 'IBS_M', 'IBS_U', name='ibstypeenum'), nullable=True),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('notification_preferences', sa.Text(), nullable=True),
    sa.Column('data_sharing_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('diet_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'BEVERAGE', name='mealtypeenum'), nullable=False),
    sa.Column('portion_size_g', sa.Float(), nullable=True),
    sa.Column('portion_description', sa.String(length=100), nullable=True),
    sa.Column('preparation_method', sa.String(length=100), nullable=True),
    sa.Column('cooking_time_minutes', sa.Integer(), nullable=True),
    sa.Column('added_ingredients', sa.Text(), nullable=True),
    sa.Column('eaten_at_home', sa.Boolean(), nullable=True),
    sa.Column('restaurant_name', sa.String(length=200), nullable=True),
    sa.Column('meal_companions', sa.Integer(), nullable=True),
    sa.Column('stress_level_before', sa.Integer(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_since_last_meal_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_diet_logs_food_id_foods')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diet_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_logs'))
    )
    op.create_index(op.f('ix_diet_logs_consumed_at'), 'diet_logs', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_diet_logs_food_id'), 'diet_logs', ['food_id'], unique=False)
    op.create_index(op.f('ix_diet_logs_id'), 'diet_logs', ['id'], unique=False)
    op.create_index(op.f('ix_diet_logs_meal_type'), 'diet_logs', ['meal_type'], unique=False)
    op.create_index(op.f('ix_diet_logs_user_id'), 'diet_logs', ['user_id'], unique=False)
    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('dosage_amount', sa.Float(), nullable=False),
    sa.Column('dosage_unit', sa.Enum('MG', 'G', 'ML', 'TABLET', 'CAPSULE', 'TEASPOON', 'TABLESPOON', 'DROP', 'SPRAY', 'PATCH', name='dosageunitenum'), nullable=False),
    sa.Column('frequency_per_day', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('adherence', sa.Enum('TAKEN', 'MISSED', 'PARTIAL', 'LATE', name='adherenceenum'), nullable=False),
    sa.Column('taken_with_food', sa.Boolean(), nullable=True),
    sa.Column('reason_for_taking', sa.String(length=200), nullable=True),
    sa.Column('effectiveness_rating', sa.Integer(), nullable=True),
    sa.Column('side_effects_experienced', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prescribed_by', sa.String(length=200), nullable=True),
    sa.Column('prescription_date', sa.DateTime(), nullable=True),
    sa.Column('prescription_duration_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_medication_logs_medication_id_medications')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medication_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_logs'))
    )
    op.create_index(op.f('ix_medication_logs_id'), 'medication_logs', ['id'], unique=False)
    op.create_index(op.f('ix_medication_logs_medication_id'), 'medication_logs', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_logs_taken_at'), 'medication_logs', ['taken_at'], unique=False)
    op.create_index(op.f('ix_medication_logs_user_id'), 'medication_logs', ['user_id'], unique=False)
    op.create_table('symptom_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'MILD', 'MODERATE', 'SEVERE', 'VERY_SEVERE', name='severityenum'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('bristol_stool_type', sa.Enum('TYPE_1', 'TYPE_2', 'TYPE_3', 'TYPE_4', 'TYPE_5', 'TYPE_6', 'TYPE_7', name='bristolstooltypeenum'), nullable=True),
    sa.Column('bowel_movement_frequency', sa.Integer(), nullable=True),
    sa.Column('pain_location', sa.String(length=100), nullable=True),
    sa.Column('pain_type', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('exercise_minutes', sa.Integer(), nullable=True),
    sa.Column('potential_triggers', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], name=op.f('fk_symptom_logs_symptom_id_symptoms')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_symptom_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptom_logs'))
    )
    op.create_index(op.f('ix_symptom_logs_id'), 'symptom_logs', ['id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_logged_at'), 'symptom_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_symptom_logs_symptom_id'), 'symptom_logs', ['symptom_id'], unique=False)
    op.create_index(op.f('ix_symptom_logs_user_id'), 'symptom_logs', ['user_id'], unique=False)
    op.create_table('food_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('diet_log_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('NONE', 'MILD', 'MODERATE', 'SEVERE', name='reactionseverityenum'), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('onset_time_minutes', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('suspected_trigger', sa.String(length=200), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('other_foods_consumed', sa.Text(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality_previous_night', sa.Integer(), nullable=True),
    sa.Column('menstrual_cycle_day', sa.Integer(), nullable=True),
    sa.Column('treatment_taken', sa.Text(), nullable=True),
    sa.Column('effectiveness_of_treatment', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reaction_occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['diet_log_id'], ['diet_logs.id'], name=op.f('fk_food_reactions_diet_log_id_diet_logs')),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_food_reactions_food_id_foods')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_food_reactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_reactions'))
    )
    op.create_index(op.f('ix_food_reactions_diet_log_id'), 'food_reactions', ['diet_log_id'], unique=False)
    op.create_index(op.f('ix_food_reactions_food_id'), 'food_reactions', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_reactions_id'), 'food_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_food_reactions_reaction_occurred_at'), 'food_reactions', ['reaction_occurred_at'], unique=False)
    op.create_index(op.f('ix_food_reactions_user_id'), 'food_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_reactions_user_id'), table_name='food_reactions')
    op.drop_index(op.f('ix_food_reactions_reaction_occurred_at'), table_name='food_reactions')
    op.drop_index(op.f('ix_food_reactions_id'), table_name='food_reactions')
    op.drop_index(op.f('ix_food_reactions_food_id'), table_name='food_reactions')
    op.drop_index(op.f('ix_food_reactions_diet_log_id'), table_name='food_reactions')
    op.drop_table('food_reactions')
    op.drop_index(op.f('ix_symptom_logs_user_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_symptom_id'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_logged_at'), table_name='symptom_logs')
    op.drop_index(op.f('ix_symptom_logs_id'), table_name='symptom_logs')
    op.drop_table('symptom_logs')
    op.drop_index(op.f('ix_medication_logs_user_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_taken_at'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_medication_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_diet_logs_user_id'), table_name='diet_logs')
    op.drop_index(op.f('ix_diet_logs_meal_type'), table_name='diet_logs')
    op.drop_index(op.f('ix_diet_logs_id'), table_name='diet_logs')
    op.drop_index(op.f('ix_diet_logs_food_id'), table_name='diet_logs')
    op.drop_index(op.f('ix_diet_logs_consumed_at'), table_name='diet_logs')
    op.drop_table('diet_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_symptoms_name'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_id'), table_name='symptoms')
    op.drop_index(op.f('ix_symptoms_category'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_medications_name'), table_name='medications')
    op.drop_index(op.f('ix_medications_medication_type'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_generic_name'), table_name='medications')
    op.drop_index(op.f('ix_medications_category'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_fodmap_level'), table_name='foods')
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
