/**
 * Report Sharing Service for IBS Analytics Reports
 * Enables sharing reports via email, social media, and direct links
 */

import { ReportData } from './pdf-generator';
import { UI_CONFIG } from './config';

export interface ShareOptions {
  platform: 'email' | 'whatsapp' | 'telegram' | 'twitter' | 'facebook' | 'linkedin' | 'copy-link';
  reportData: ReportData;
  recipientEmail?: string;
  message?: string;
  includePersonalData?: boolean;
}

export interface ShareableReport {
  id: string;
  title: string;
  summary: string;
  shareUrl: string;
  expiresAt: Date;
  isPublic: boolean;
  accessCount: number;
}

export class ReportSharingService {
  private baseUrl: string;
  private apiEndpoint: string;

  constructor() {
    this.baseUrl = typeof window !== 'undefined' ? window.location.origin : 'https://ibs-wellness.com';
    this.apiEndpoint = '/api/reports/share';
  }

  /**
   * Generate a shareable link for the report
   */
  async generateShareableLink(reportData: ReportData, options: {
    expiresInDays?: number;
    isPublic?: boolean;
    includePersonalData?: boolean;
  } = {}): Promise<ShareableReport> {
    try {
      const {
        expiresInDays = 7,
        isPublic = false,
        includePersonalData = false
      } = options;

      // Sanitize report data if personal data should not be included
      const sanitizedData = includePersonalData ? reportData : this.sanitizeReportData(reportData);

      const shareData = {
        reportData: sanitizedData,
        expiresInDays,
        isPublic,
        includePersonalData
      };

      // In a real implementation, this would make an API call to your backend
      const response = await this.mockApiCall('/api/reports/share', 'POST', shareData);
      
      return {
        id: response.shareId,
        title: `IBS Wellness Report - ${reportData.user_summary.name}`,
        summary: this.generateReportSummary(reportData),
        shareUrl: `${this.baseUrl}/shared-reports/${response.shareId}`,
        expiresAt: new Date(Date.now() + expiresInDays * 24 * 60 * 60 * 1000),
        isPublic,
        accessCount: 0
      };
    } catch (error) {
      console.error('Error generating shareable link:', error);
      throw new Error('Failed to generate shareable link');
    }
  }

  /**
   * Share report via different platforms
   */
  async shareReport(options: ShareOptions): Promise<boolean> {
    try {
      const { platform, reportData, recipientEmail, message } = options;

      switch (platform) {
        case 'email':
          return await this.shareViaEmail(reportData, recipientEmail, message);
        
        case 'whatsapp':
          return this.shareViaWhatsApp(reportData, message);
        
        case 'telegram':
          return this.shareViaTelegram(reportData, message);
        
        case 'twitter':
          return this.shareViaTwitter(reportData, message);
        
        case 'facebook':
          return this.shareViaFacebook(reportData, message);
        
        case 'linkedin':
          return this.shareViaLinkedIn(reportData, message);
        
        case 'copy-link':
          return await this.copyLinkToClipboard(reportData);
        
        default:
          throw new Error(`Unsupported sharing platform: ${platform}`);
      }
    } catch (error) {
      console.error(`Error sharing report via ${options.platform}:`, error);
      return false;
    }
  }

  /**
   * Share report via email
   */
  private async shareViaEmail(reportData: ReportData, recipientEmail?: string, customMessage?: string): Promise<boolean> {
    try {
      const shareableReport = await this.generateShareableLink(reportData, { includePersonalData: false });
      
      const subject = encodeURIComponent('IBS Wellness Report - Health Insights');
      const body = encodeURIComponent(
        `${customMessage || 'I wanted to share my IBS wellness report with you.'}\n\n` +
        `Report Summary: ${shareableReport.summary}\n\n` +
        `View the full report: ${shareableReport.shareUrl}\n\n` +
        `This link will expire on ${shareableReport.expiresAt.toLocaleDateString()}.\n\n` +
        `Generated by IBS Wellness Companion`
      );

      if (recipientEmail) {
        // In a real implementation, send email via backend API
        await this.mockApiCall('/api/reports/send-email', 'POST', {
          to: recipientEmail,
          subject: 'IBS Wellness Report - Health Insights',
          body: body,
          shareUrl: shareableReport.shareUrl
        });
        return true;
      } else {
        // Open default email client
        const mailtoUrl = `mailto:?subject=${subject}&body=${body}`;
        window.open(mailtoUrl, '_blank');
        return true;
      }
    } catch (error) {
      console.error('Error sharing via email:', error);
      return false;
    }
  }

  /**
   * Share report via WhatsApp
   */
  private shareViaWhatsApp(reportData: ReportData, customMessage?: string): boolean {
    try {
      const message = encodeURIComponent(
        `${customMessage || 'Check out my IBS wellness report!'}\n\n` +
        `${this.generateReportSummary(reportData)}\n\n` +
        `Generated by IBS Wellness Companion 🏥`
      );

      const whatsappUrl = `https://wa.me/?text=${message}`;
      window.open(whatsappUrl, '_blank');
      return true;
    } catch (error) {
      console.error('Error sharing via WhatsApp:', error);
      return false;
    }
  }

  /**
   * Share report via Telegram
   */
  private shareViaTelegram(reportData: ReportData, customMessage?: string): boolean {
    try {
      const message = encodeURIComponent(
        `${customMessage || 'My IBS wellness report insights:'}\n\n` +
        `${this.generateReportSummary(reportData)}\n\n` +
        `#IBSWellness #HealthTracking`
      );

      const telegramUrl = `https://t.me/share/url?text=${message}`;
      window.open(telegramUrl, '_blank');
      return true;
    } catch (error) {
      console.error('Error sharing via Telegram:', error);
      return false;
    }
  }

  /**
   * Share report via Twitter
   */
  private shareViaTwitter(reportData: ReportData, customMessage?: string): boolean {
    try {
      const message = encodeURIComponent(
        `${customMessage || 'Tracking my IBS wellness journey! 📊'}\n\n` +
        `Current trend: ${reportData.user_summary.overall_trend}\n` +
        `Symptom control: ${reportData.progress_metrics.symptom_control}%\n\n` +
        `#IBSWellness #HealthTracking #WellnessJourney`
      );

      const twitterUrl = `https://twitter.com/intent/tweet?text=${message}`;
      window.open(twitterUrl, '_blank');
      return true;
    } catch (error) {
      console.error('Error sharing via Twitter:', error);
      return false;
    }
  }

  /**
   * Share report via Facebook
   */
  private shareViaFacebook(reportData: ReportData, customMessage?: string): boolean {
    try {
      const message = encodeURIComponent(
        `${customMessage || 'Sharing my health progress! 💪'}\n\n` +
        `My IBS wellness journey shows ${reportData.user_summary.overall_trend} trends.\n` +
        `Quality of life improvement: ${reportData.progress_metrics.quality_of_life}%`
      );

      const facebookUrl = `https://www.facebook.com/sharer/sharer.php?quote=${message}`;
      window.open(facebookUrl, '_blank');
      return true;
    } catch (error) {
      console.error('Error sharing via Facebook:', error);
      return false;
    }
  }

  /**
   * Share report via LinkedIn
   */
  private shareViaLinkedIn(reportData: ReportData, customMessage?: string): boolean {
    try {
      const message = encodeURIComponent(
        `${customMessage || 'Leveraging technology for better health outcomes! 🏥'}\n\n` +
        `Using AI-powered insights to manage IBS symptoms effectively.\n` +
        `Current progress: ${reportData.progress_metrics.goal_achievement}% goal achievement.\n\n` +
        `#HealthTech #DigitalHealth #IBSManagement #WellnessTechnology`
      );

      const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?summary=${message}`;
      window.open(linkedinUrl, '_blank');
      return true;
    } catch (error) {
      console.error('Error sharing via LinkedIn:', error);
      return false;
    }
  }

  /**
   * Copy shareable link to clipboard
   */
  private async copyLinkToClipboard(reportData: ReportData): Promise<boolean> {
    try {
      const shareableReport = await this.generateShareableLink(reportData, { includePersonalData: false });
      
      if (navigator.clipboard && window.isSecureContext) {
        await navigator.clipboard.writeText(shareableReport.shareUrl);
      } else {
        // Fallback for older browsers
        const textArea = document.createElement('textarea');
        textArea.value = shareableReport.shareUrl;
        document.body.appendChild(textArea);
        textArea.focus();
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
      }
      
      return true;
    } catch (error) {
      console.error('Error copying link to clipboard:', error);
      return false;
    }
  }

  /**
   * Generate a summary of the report for sharing
   */
  private generateReportSummary(reportData: ReportData): string {
    const { user_summary, severity_assessment, progress_metrics, ml_predictions } = reportData;
    
    return `📊 IBS Wellness Report Summary\n` +
           `👤 Patient: ${user_summary.name}\n` +
           `📈 Overall Trend: ${user_summary.overall_trend}\n` +
           `🎯 Severity Score: ${severity_assessment.current_score}/10\n` +
           `💪 Symptom Control: ${progress_metrics.symptom_control}%\n` +
           `🌟 Quality of Life: ${progress_metrics.quality_of_life}%\n` +
           `⚠️ Flare-up Risk: ${ml_predictions.flareup_risk}%\n` +
           `📅 Generated: ${new Date().toLocaleDateString()}`;
  }

  /**
   * Remove personal information from report data for sharing
   */
  private sanitizeReportData(reportData: ReportData): ReportData {
    return {
      ...reportData,
      user_summary: {
        ...reportData.user_summary,
        name: 'Anonymous User',
        // Keep other non-personal fields
      }
    };
  }

  /**
   * Mock API call for demonstration (replace with actual API calls)
   */
  private async mockApiCall(endpoint: string, method: string, data?: any): Promise<any> {
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, UI_CONFIG.DELAY_MEDIUM));
    
    // Mock response based on endpoint
    if (endpoint === '/api/reports/share') {
      return {
        shareId: `share_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        success: true
      };
    }
    
    if (endpoint === '/api/reports/send-email') {
      return {
        messageId: `msg_${Date.now()}`,
        success: true
      };
    }
    
    return { success: true };
  }

  /**
   * Get sharing analytics for a report
   */
  async getShareAnalytics(shareId: string): Promise<{
    totalViews: number;
    uniqueViews: number;
    platforms: Record<string, number>;
    lastAccessed: Date;
  }> {
    try {
      // Mock analytics data
      return {
        totalViews: Math.floor(Math.random() * 50) + 1,
        uniqueViews: Math.floor(Math.random() * 30) + 1,
        platforms: {
          direct: Math.floor(Math.random() * 10),
          email: Math.floor(Math.random() * 15),
          whatsapp: Math.floor(Math.random() * 8),
          social: Math.floor(Math.random() * 5)
        },
        lastAccessed: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000)
      };
    } catch (error) {
      console.error('Error fetching share analytics:', error);
      throw error;
    }
  }
}

// Utility functions
export const shareReport = async (options: ShareOptions): Promise<boolean> => {
  const sharingService = new ReportSharingService();
  return await sharingService.shareReport(options);
};

export const generateShareableLink = async (reportData: ReportData, options?: {
  expiresInDays?: number;
  isPublic?: boolean;
  includePersonalData?: boolean;
}): Promise<ShareableReport> => {
  const sharingService = new ReportSharingService();
  return await sharingService.generateShareableLink(reportData, options);
};

export const copyReportLink = async (reportData: ReportData): Promise<boolean> => {
  const sharingService = new ReportSharingService();
  return await sharingService.shareReport({
    platform: 'copy-link',
    reportData
  });
};